DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS PET;
  
CREATE TABLE USER (
  id INT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(50) DEFAULT NULL
);

CREATE TABLE PET (
  id INT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  species VARCHAR(50) NOT NULL,
  user_id INT, 
  FOREIGN KEY(user_id) REFERENCES user(id) 
);