INSERT INTO PET (id, name, species, user_id) VALUES
    (1, 'Molly', 'Dog (Beagle)', 1),
    (2, 'Shadow', 'Cat (British Longhair)', 1),
    (3, 'Lucky', 'Budgie ', 1),
    (4, 'Harley', 'Dog (Husky)', 2),
    (5, 'Maggie', 'Bunny', 3),
    (6, 'Princess', 'Cat (Siamese)', 4),
    (8, 'Angel', 'Dog (Golden Retriever)', 4),
    (9, 'Coco', 'Cat (Aegean)', 5),
    (10, 'Gizmo', 'Neon Tetra', 5),
    (11, 'Roxy', 'Dog (Irish Setter)', 5),
    (12, 'Buster', 'Tarantula', 6),
    (13, 'Ginger', 'Cat (Birman)', 6),
    (14, 'Pepper', 'Guinea Pig', 7),
    (15, 'Teddy', 'Dog (Poodle)', 7),
    (16, 'Shelby', 'Pigeon', 7),
    (17, 'Misty', 'Cat (American Curl)', 7);